CHANGELOG.md, build.sbt, modules/core/src/main/scala/com/azavea/stac4s/core/Bbox.scala, modules/core/src/main/scala/com/azavea/stac4s/core/ItemCollection.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacAsset.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacCatalog.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacCollection.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacExtent.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacItem.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacLicense.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacLink.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacLinkType.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacMediaType.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacProvider.scala, modules/core/src/main/scala/com/azavea/stac4s/core/StacProviderRole.scala, modules/core/src/main/scala/com/azavea/stac4s/core/package.scala, modules/core/src/main/scala/com/azavea/stac4s/meta/package.scala, modules/core/src/test/scala/com/azavea/stac4s/core/Generators.scala, modules/core/src/test/scala/com/azavea/stac4s/core/SerDeSpec.scala, project/Versions.scala
Updates to latest GeoTrellis - 3.2 and includes updated Cats dependencies.
Also renames packages to remove `core` from the name to make it less onerous to use.
Lastly, adds `toExtent` method to `Bbox` to streamline `extent` <-> `bbox` conversion
~- [ ] New tests have been added or existing tests have been modified~
I think this should signal the next release as `0.0.3` so that we can test using this when we upgrade Franklin and `Raster Foundry`
=> Update dependencies, rename package, add missing Bbox functionality

.circleci/config.yml, scripts/cipublish
This PR changes the `sonatypeOpen` command no longer to have an argument, since it seems like it doesn't expect one.
- ~New tests have been added or existing tests have been modified~
- it works! https://app.circleci.com/pipelines/github/azavea/stac4s/154/workflows/67160d33-19b2-469b-9c97-11b75fa8f697/jobs/181/steps
- proof: add the `0.0.7-bugfix2` dependency to one of your scala projects and check where it gets resolved from
Closes #53
=> Fix sonatype publication

CHANGELOG.md, modules/core/src/test/scala/com/azavea/stac4s/Generators.scala
This PR makes it so that bboxes and other classes requiring doubles are guaranteed finite doubles. It prevents flaky test results where `NaN != NaN` was causing equality expectations to fail.
=> Only gen finite doubles

CHANGELOG.md, build.sbt, modules/core/src/main/scala/com/azavea/stac4s/extensions/eo/Band.scala, modules/core/src/main/scala/com/azavea/stac4s/extensions/eo/EOAssetExtension.scala, modules/core/src/main/scala/com/azavea/stac4s/extensions/eo/EOItemExtension.scala, modules/core/src/main/scala/com/azavea/stac4s/extensions/eo/package.scala, modules/core/src/test/scala/com/azavea/stac4s/Generators.scala, modules/core/src/test/scala/com/azavea/stac4s/SerDeSpec.scala, modules/core/src/test/scala/com/azavea/stac4s/SyntaxSpec.scala
This PR adds case classes and typeclass evidence + tests for parsing the [EO extension](https://github.com/radiantearth/stac-spec/tree/master/extensions/eo).
I made every field in `Band` required. In the spec every field is optional. That's [formally an oversight](https://gitter.im/SpatioTemporal-Asset-Catalog/Lobby?at=5ec57dfe9d1d2310cc38cf74). It's easy enough to make things optional later once someone has opinions about which fields if any should be required, so I'm ignoring the problem for now and demanding full bands. I could be talked into making `description` and the two wavelength indicators optional.
Closes #72
=> Parse EO extension

CHANGELOG.md, modules/core/src/main/scala/com/azavea/stac4s/StacAssetRole.scala, modules/core/src/main/scala/com/azavea/stac4s/StacLinkType.scala, modules/core/src/main/scala/com/azavea/stac4s/StacMediaType.scala, modules/core/src/main/scala/com/azavea/stac4s/extensions/label/LabelMethod.scala, modules/core/src/main/scala/com/azavea/stac4s/extensions/label/LabelTask.scala, modules/core/src/test/resources/catalogs/landsat-stac-layers/landsat-8-l1/2014-153/LC81530252014153LGN00.json, modules/core/src/test/resources/catalogs/landsat-stac/landsat-8-l1/2014-153/LC81530252014153LGN00.json, modules/core/src/test/scala/com/azavea/stac4s/Generators.scala
This PR:
- makes the `VendorFoo` enums for link types, media types, label tasks, label methods, and asset roles consistent (`extends Foo(s)` instead of `extends Foo("vendor")`)
- adds a missing `StacLinkType` to the known list
- tests
Closes #68 
Closes #66
=> Fix vendor serde and missing link type

CHANGELOG.md, modules/core/src/main/scala/com/azavea/stac4s/StacCollection.scala
This PR makes decoding `properties` in collection json optional. It's still required on the object but not required in the input json. It's a bug that would have been caught by circe-golden (#88) I think if we were using it :(
- ~New tests have been added or existing tests have been modified~
=> Make properties field optional on collections

.circleci/config.yml, CHANGELOG.md
This retrieves an up-to-date copy of the Azavea public GPG key during the `run_cipublish` build stage.
The CircleCI build will now retrieve the latest copy of the public key, allowing us to renew the key in the future by pushing a new signature with an extended expiration date to public keyservers.
~- [ ] New tests have been added or existing tests have been modified~
- Verify that a valid Azavea GPG key is retrieved from a public keyserver and verified during `run_cipublish`.
- This key was retrieved in [this job run](https://circleci.com/gh/azavea/stac4s/262).
Connects azavea/operations#446
=> Receive GPG key while publishing artifacts

CHANGELOG.md, modules/core/src/main/scala/com/azavea/stac4s/StacCatalog.scala
This PR makes `stac_extensions` optional when decoding catalogs.
- make sure that everywhere we try to get a field named `stac_extensions` when decoding, we ask for an `Option[List[String]]` instead of a `List[String]`
Closes #121
=> Extensions are not required on catalogs

CHANGELOG.md, modules/testing/src/main/scala/testing.scala
This PR updates the bbox generators so that the results are spatially valid bboxes (min values are always less than max values)
- [NA] New tests have been added or existing tests have been modified
=> Make Bbox generators always output valid Bboxes

.gitignore
After upgrade to sbt 1.4.*, we have a nice .bsp directory. We don't want it committed and it's just `git status` noise.
- ~Changelog updated~
=> Ignore .bsp

CHANGELOG.md, build.sbt, scripts/cipublish, scripts/test
This PR fixes the `root` project so that it's no longer a cross project. This is necessary to get sonatype sbt to cooperate.
See [build log](https://app.circleci.com/pipelines/github/azavea/stac4s/475/workflows/cfa0cfc8-f61b-4139-bdaa-f06a4546aff8/jobs/541) for evidence
=> Fix package publication

.circleci/config.yml, CHANGELOG.md, README.md, docs/stac-api-spec/extensions/layer/README.md, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/catalog.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/landsat-8-l1/2018-05/LC80150322018141LGN00.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/landsat-8-l1/2018-06/LC80140332018166LGN00.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/landsat-8-l1/2018-06/LC80300332018166LGN00.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/landsat-8-l1/2018-07/LC80150332018189LGN00.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/landsat-8-l1/catalog.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/layers/catalog.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/layers/pa.json, docs/stac-spec/extensions/layer/examples/landsat-stac-layers/layers/us.json, modules/core/shared/src/main/scala/com/azavea/stac4s/meta/ValidStacVersion.scala, modules/testing/js/src/main/scala/JsInstances.scala, modules/testing/jvm/src/main/scala/JvmInstances.scala
Our release instructions include `chan gh-release <semver>`. Unfortunately, this pushes a tag starting with `v`, so we end up double-publishing the version we're releasing. With this PR, Circle ignores those tags:
It's not perfect... the `gh-release` creates links between the `v` tags that `chan` likes, so we can't delete those without breaking the links in the `gh-release`. I'm not totally sure what to do here, so I'm going to leave things up and hope to talk about it next week.
=> Only deploy tags if they start with `v`

CHANGELOG.md, modules/client/shared/src/test/scala/com/azavea/stac4s/api/client/SttpStacClientFSpec.scala, modules/client/shared/src/test/scala/org/scalacheck/resample/package.scala
This PR:
- Makes tests more prescise (i.e. empty list result is an expected result and should not fail)
- Removes `generator.sample.get` calls with the `resample` function taken from here: https://github.com/typelevel/scalacheck/issues/650#issuecomment-625384900
Closes #211
=> Review client specs and make them more deterministic

CHANGELOG.md, modules/core-test/jvm/src/test/scala/com/azavea/stac4s/JvmSerDeSpec.scala, modules/core-test/shared/src/test/scala/com/azavea/stac4s/SerDeSpec.scala, modules/core/js/src/main/scala/com/azavea/stac4s/extensions/layer/StacLayer.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/extensions/layer/StacLayer.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/extensions/layer/StacLayerProperties.scala, modules/testing/js/src/main/scala/JsInstances.scala, modules/testing/jvm/src/main/scala/JvmInstances.scala, modules/testing/shared/src/main/scala/TestInstances.scala
This PR adds a `StacLayer` and `StacLayerProperties` type to support API extension work in Franklin.
I opted to remove `stac_extensions` from these entities. Making them extensible makes layers overloadable for lots of purposes, which I think Maybe Bad :tm: -- getting rid of extensions and requiring the start and end datetime fields means that `StacLayers` can be used for one thing and one thing only, which I think is a good outcome. Pending review I'll make the same change in azavea/stac-layers
helps with geotrellis/geotrellis-server#316
=> Add and test layer types

build.sbt
Signed-off-by: philvarner <philvarner@gmail.com>
The build includes the paradise macro compiler plugin, but there doesn't seem to be any code that uses it -- at least, removing still results in a successful build and test run. This requires a version-dependent switch for cross-compilation between 2.12 and 2.13. The plugin was added in commit 135006a with other changes intended to get publishing to Sonatype working, but seems unrelated. 
The motivation for this is to add support for cross-compilation against 2.13 for when geotrellis eventually has a 2.13 release available for vector, raster, and utils. 
none
=> remove paradise compiler plugin, as it does not seem to be used

CHANGELOG.md, modules/core-test/js/src/test/scala/com/azavea/stac4s/JsFPLawsSpec.scala, modules/core-test/jvm/src/test/scala/com/azavea/stac4s/JvmFPLawsSpec.scala, modules/core-test/jvm/src/test/scala/com/azavea/stac4s/JvmSerDeSpec.scala, modules/core/js/src/main/scala/com/azavea/stac4s/Bbox.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/Bbox.scala
This PR makes bboxes unionable. I don't know why I didn't give them a semigroup. I should just give them a semigroup. I'll do that tomorrow. 🤦🏻‍♂️
A release including this PR blocks https://github.com/azavea/franklin/pull/623
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
Closes #XXX (if applicable)
=> Union bboxes

CHANGELOG.md, modules/core-test/shared/src/test/scala/com/azavea/stac4s/BboxSpec.scala, modules/testing/shared/src/main/scala/TestInstances.scala
I'm calling these tests "bbox laws." I added these to deal with some downstream test failures that I wasn't expecting in azavea/franklin#623. It turns out the bbox union isn't the problem, but it's still useful to include these tests
=> Test bbox laws

CHANGELOG.md, build.sbt, modules/core-test/jvm/src/test/scala/com/azavea/stac4s/JvmSerDeSpec.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/StacExtent.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/extensions/IntervalExtension.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/extensions/periodic/PeriodicExtent.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/meta/ForeignImplicits.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/syntax/package.scala, modules/testing/jvm/src/main/scala/JvmInstances.scala, project/Versions.scala
This PR:
- makes `Intervals` extensible with the `InteralExtension` typeclass
- models the periodic extension to intervals with the `PeriodicExtent` type
- adds tests for all this stuff
I skipped JS. This extension is experimental, and as much fun as simple time types were, I was not super interested in more complicated time types. If we get good use out of this extension and discover we need it in js, we can add it then.
Closes #268
=> Model periodic intervals

.circleci/config.yml, CHANGELOG.md, modules/core/shared/src/main/scala/com/azavea/stac4s/meta/ValidStacVersion.scala, modules/testing/js/src/main/scala/JsInstances.scala, modules/testing/jvm/src/main/scala/JvmInstances.scala, modules/testing/shared/src/main/scala/TestInstances.scala
This PR bounds the asset map generators for items and collections so they don't consume hilarious amounts of memory and break downstream tests.
Tested with local publication and Franklin where the problem was occurring. Will merge / release post-CI.
Closes #289
=> Bound asset map generators

CHANGELOG.md, modules/core/jvm/src/main/scala/com/azavea/stac4s/StacCollection.scala, modules/testing/jvm/src/main/scala/JvmInstances.scala
This PR corrects an omission where the JVM `StacCollection` `_type` field was missing. This adds the field, decodes it, and adds it to generators.
=> Decode collection type field in JVM

CHANGELOG.md, modules/core/js/src/main/scala/com/azavea/stac4s/StacCollection.scala, modules/core/js/src/main/scala/com/azavea/stac4s/StacItem.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/StacCollection.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/StacItem.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/ItemCollection.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacAsset.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacCatalog.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacLink.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacProvider.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/extensions/eo/Band.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/extensions/eo/EOItemExtension.scala
This PR makes encoders aware of whether nulls should be dropped. For example, in links, `null`s are just nuisance data, so they should be dropped, while in intervals, they _mean something_, so they should not be dropped. I've published locally and consumed in Franklin with the data I have locally, and this change makes the responses valid according to `stac-node-validator` up to the values in `stac_extensions`, which is not `stac4s`'es responsibility.
- ~New tests have been added or existing tests have been modified~
=> Selectively drop nulls in encoders

CHANGELOG.md, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/SttpStacClient.scala, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/package.scala, modules/client/js/src/test/scala/com/azavea/stac4s/api/client/SttpStacClientSpec.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/SttpStacClient.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/client.scala, modules/client/jvm/src/test/scala/com/azavea/stac4s/api/client/SttpStacClientSpec.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/StacClientF.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/SttpStacClientF.scala, modules/client/shared/src/test/scala/com/azavea/stac4s/api/client/SttpStacClientFSpec.scala
This PR updates SearchFilters codecs (see https://github.com/azavea/franklin/pull/708) as well as simplifies the StacClient interface making it 'simple'. The type memeber is removed and moved into the type parameter. Without this PR it would be hard to work with such interface and mix logging on the client side (see the POC https://github.com/geotrellis/geotrellis-server/pull/367/files)
=> Update StacClient and SearchFilters JSON codecs

.circleci/config.yml, CHANGELOG.md, build.sbt, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/utils/ClientCodecs.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/utils/ClientCodecs.scala, modules/core/js/src/main/scala/com/azavea/stac4s/meta/ForeignImplicits.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/meta/ForeignImplicits.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/ProductFieldNames.scala, project/Versions.scala, sbt, scripts/cipublish, scripts/test
This PR adds Scala 2.13 cross compilation and adjusts the CI to run tests against Scala 2.13. 
However, it would not push 2.13 release artifacts into the sonatype since 2.13 artifacts require GT SNAPSHOT deps.
Closes #77
=> Add Scala 2.13 cross compilation

CHANGELOG.md, build.sbt, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/StacClient.scala, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/package.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/StacClient.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/client.scala
This PR makes `StacClient` a trait and not a type alias, otherwise client children is really inconvenient to define:
i.e. right now it is:
```scala
class StacClientLoggingMid[F[_]] extends StacClientF[Mid[F, *], SearchFilters]
```
with this PR it becomes:
```scala
class StacClientLoggingMid[F[_]] extends StacClient[Mid[F, *]]
```
=> Make StacClient type alias a trait

CHANGELOG.md, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/util/ClientCodecs.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/util/ClientCodecs.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/ETag.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/StacClientF.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/SttpStacClientF.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/util/syntax/package.scala, modules/client/shared/src/test/scala/com/azavea/stac4s/api/client/SttpStacClientFSpec.scala, modules/client/shared/src/test/scala/com/azavea/stac4s/api/client/SttpSyntax.scala
This PR finishes the StacAPIClient functionality. 
[STAC Catalog Update flow example](https://gist.github.com/pomadchin/86e61dc151fbf2be9fa9f824473071b7#file-staccatalogupdate-scala-L66-L90)
=> Add STACClient itemUpdate, itemPatch and itemDelete methods

.circleci/config.yml
This PR cleans up the CircleCI yaml file. I realized that we can use the natural supported `environment` construct instead of using bash global vars.
=> Cleanup CircleCI syntax

CHANGELOG.md, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/SttpStacClientF.scala
This PR allows the base STAC API URI to have paths.
=> Replace withPath with addPath to allow paths in the STAC API URI

CHANGELOG.md, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/SttpStacClientF.scala
This PR sets content type to all client post requests as well as adjusts SearchFilters (make all fields optional + drop nulls in requests) case class to make client more compatible with different STAC API Implementations.
=> Add a correct content type to POST requests and SearchFilters adjustments

CHANGELOG.md, modules/core-test/shared/src/test/scala/com/azavea/stac4s/SerDeSpec.scala, modules/core/js/src/main/scala/com/azavea/stac4s/StacCollection.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/StacCollection.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacAsset.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacCatalog.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/StacLink.scala
This PR defines `apply` in terms of `decodeAccumulating` to ensure the behavior of `decodeAccumulating` is correct. Previously `decodeAccumulating` relied on the default implementation for a codec with an `apply` defined, which takes the `Result` (an `Either`) and wraps the error in a `ValidatedNel` if present: https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L50-L60. Here instead we flip it.
We didn't accumulate errors previously despite using `mapN` because `c.get` returns an `Either`, and `Either`'s applicative doesn't accumulate 🕵🏻‍♂️
Closes #372
=> Ensure json errors accumulate for custom decoders

build.sbt, project/Versions.scala
This PR resolves the current CI run issues.
=> Bump JTS version up to 1.17.0 in the Scala 2.13 release

CHANGELOG.md, modules/core-test/js/src/test/scala/com/azavea/stac4s/JsSerDeSpec.scala, modules/core-test/jvm/src/test/scala/com/azavea/stac4s/JvmSerDeSpec.scala, modules/core-test/shared/src/test/scala/com/azavea/stac4s/SerDeSpec.scala, modules/core/js/src/main/scala/com/azavea/stac4s/StacItem.scala, modules/core/jvm/src/main/scala/com/azavea/stac4s/StacItem.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/ItemDatetime.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/ItemProperties.scala, modules/core/shared/src/main/scala/com/azavea/stac4s/types.scala, modules/testing/js/src/main/scala/JsInstances.scala, modules/testing/jvm/src/main/scala/JvmInstances.scala, modules/testing/shared/src/main/scala/TestInstances.scala
This PR switches from a sum type to cats's [`Ior`](https://typelevel.org/cats/datatypes/ior.html) type for encoding item datetimes.
Helps with azavea/franklin#960
=> Allow items to have both time ranges point in time datetimes

CHANGELOG.md, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/StacClientF.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/SttpStacClientF.scala
This PR adds a convenient extra overload.
=> Expose client.search overload with an optional filter argument

.circleci/config.yml, CHANGELOG.md, build.sbt, modules/client/js/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/jvm/src/main/scala/com/azavea/stac4s/api/client/SearchFilters.scala, modules/client/shared/src/main/scala/com/azavea/stac4s/api/client/SttpStacClientF.scala
This PR makes SearchFilters case class pagination agnostic. It complements https://github.com/azavea/stac4s/pull/496.
=> Make SearchFilters pagination agnostic

.circleci/config.yml
This PR updates deployments to run for scala 2.13
=> Fix circle deploy for 2.13
